name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        # Tenta ajudar o cache a achar o pom, mas o principal é nos passos abaixo
        # cache-dependency-path: '**/pom.xml' 

    - name: Build with Maven
      # Executa o comando DENTRO da subpasta
      run: mvn -B package --file pom.xml
      working-directory: atividade-sd # <--- ADICIONE ESTA LINHA

    - name: Test with Maven
      # Executa o comando DENTRO da subpasta
      run: mvn test --file pom.xml
      working-directory: atividade-sd # <--- ADICIONE ESTA LINHA